spring:
  application:
    name: eureka-server

server:
  port: 8761

logging:
  level:
    com.netflix: DEBUG # leaving com.netflix name on one line because it's a package name

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49
    enable-self-preservation: true